### ISSUE TITLE
MissingPluginException(No implementation found for method initial on channel image_vision)

### ISSUE THREAD

**Issue by kyaw-thant-zin** [alishe79/image_vision#2]
Unhandled Exception: MissingPluginException(No implementation found for method initial on channel image_vision)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
<asynchronous suspension>
#1      MethodChannelImageVision.initial (package:image_vision/image_vision_method_channel.dart:14:18)

I got this error in Mac M1. I can run the app but not working.

**Comment by alishe79** [comment]
please do not use hot reload and and hot restart, close app and run again
